# Add 'Seach Api' to changes in search api
'Seach Api':
  - app/SearchApi/**/*

# Add 'Dynamics Adapter' to changes in dynamics adapter
'Dynamics Adapter':
  - app/DynamicsAdapter/**/*

# Add 'DevOps' to changes in openshift folder
'DevOps':
  - openshift/**/*
