version: "3.7"
services:

  splunk:
    image: splunk/splunk:8.0.2.1
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/3119/release/1.4.0/download
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}
      - SPLUNKBASE_PASSWORD=${SPLUNKBASE_PASSWORD}
    ports:
      - "8000:8000"
    networks:
      - search-api-net

  splunk-init:
    build:
      context: ./splunk
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
    networks:
      - search-api-net

  search-api:
    build:
      context: app/SearchApi
      args:
        PROJECT_NAME: SearchApi.Web
        NEXUS_REPO_URL: ${NEXUS_REPO_URL}
        NEXUS_REPO_USER: ${NEXUS_REPO_USER}
        NEXUS_REPO_PASSWORD: ${NEXUS_REPO_PASSWORD}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: guest
      RABBITMQ__PASSWORD: guest
      JAEGER_SERVICE_NAME: search-api
      JAEGER_SAMPLER_TYPE: const
      REDIS__PASSWORD: ${REDIS__PASSWORD}
      REDIS__CONNECTTIMEOUT: 6000
      REDIS__CONNECTRETRY: 2
      REDIS__HOSTS__0__HOST: ${REDIS__HOST}
      REDIS__HOSTS__0__PORT: 6379
      REDIS__ABORTONCONNECTFAIL: "false"
      REDIS__SYNCTIMEOUT: 5000
      REDIS__CONNECTTIMEOUT: 6000
      DEEPSEARCH__MAXWAVECOUNT: 4
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
      SEARCHAPI__WEBHOOKS__0__NAME: dynadapter
      SEARCHAPI__WEBHOOKS__0__URI: http://dynadapter/PersonSearch
      SPLUNK_COLLECTOR_URL: https://splunk:8088
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}
    ports:
      - "5050:80"
    restart: always
    networks:
      - search-api-net

  sample-request-adapter:
    build:
      context: app/SearchApi
      args:
        PROJECT_NAME: AgencyAdapter.Sample
        NEXUS_REPO_URL: ${NEXUS_REPO_URL}
        NEXUS_REPO_USER: ${NEXUS_REPO_USER}
        NEXUS_REPO_PASSWORD: ${NEXUS_REPO_PASSWORD}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: guest
      RABBITMQ__PASSWORD: guest
      JAEGER_SERVICE_NAME: sample-adapter
      JAEGER_SAMPLER_TYPE: const
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
    ports:
      - "5053:80"
    restart: always
    networks:
      - search-api-net
  sample-adapter:
    build:
      context: app/SearchApi
      args:
        PROJECT_NAME: SearchAdapter.Sample
        NEXUS_REPO_URL: ${NEXUS_REPO_URL}
        NEXUS_REPO_USER: ${NEXUS_REPO_USER}
        NEXUS_REPO_PASSWORD: ${NEXUS_REPO_PASSWORD}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: guest
      RABBITMQ__PASSWORD: guest
      JAEGER_SERVICE_NAME: sample-adapter
      JAEGER_SAMPLER_TYPE: const
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
    ports:
      - "5052:80"
    restart: always
    networks:
      - search-api-net

  dynadapter:
    build:
      context: app/DynamicsAdapter
      args: 
        PROJECT_NAME: DynamicsAdapter.Web
        NEXUS_REPO_URL: ${NEXUS_REPO_URL}
        NEXUS_REPO_USER: ${NEXUS_REPO_USER}
        NEXUS_REPO_PASSWORD: ${NEXUS_REPO_PASSWORD}
    ports:
      - "5060:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      JAEGER_SERVICE_NAME: Dynadpater
      JAEGER_SAMPLER_TYPE: const
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
      SCHEDULER__CRON: 0/5 * * * * ?
      SCHEDULER_FAILED: 0 30 11 * * ? *
      SEARCHAPI__BASEURL: http://search-api
      SEARCHAPI_AVAILABLEDATAPARTNER: ""
      OAUTH__OAUTHURL: ${OAUTH__OAUTHURL}
      OAUTH__RESOURCEURL: ${OAUTH__RESOURCEURL}
      OAUTH__CLIENTID: ${OAUTH__CLIENTID}
      OAUTH__SECRET: ${OAUTH__SECRET}
      OAUTH__USERNAME: ${OAUTH__USERNAME}
      OAUTH__PASSWORD: ${OAUTH__PASSWORD}
      APIGATEWAY__BASEPATH: ${APIGATEWAY__BASEPATH}
      SPLUNK_COLLECTOR_URL: https://splunk:8088
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
      REDIS__CONNECTTIMEOUT: 6000
      REDIS__CONNECTRETRY: 2
      REDIS__HOSTS__0__HOST: ${REDIS__HOST}
      REDIS__HOSTS__0__PORT: 6379
      REDIS__ABORTONCONNECTFAIL: "false"
      REDIS__SYNCTIMEOUT: 5000
      REDIS__CONNECTTIMEOUT: 6000
    restart: always
    networks:
      - search-api-net
  request-api:
    build:
      context: app/SearchApi
      args: 
        PROJECT_NAME: SearchRequest.Adaptor
        NEXUS_REPO_URL: ${NEXUS_REPO_URL}
        NEXUS_REPO_USER: ${NEXUS_REPO_USER}
        NEXUS_REPO_PASSWORD: ${NEXUS_REPO_PASSWORD}
    ports:
      - "5070:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: guest
      RABBITMQ__PASSWORD: guest
      JAEGER_SERVICE_NAME: search-api
      JAEGER_SAMPLER_TYPE: const
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
      SearchRequestAdaptor__WebHooks__0__Name: dynadapter
      SearchRequestAdaptor__WebHooks__0__Uri: http://dynadapter/AgencyRequest
      SPLUNK_COLLECTOR_URL: https://splunk:8088
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}
    restart: always
    networks:
      - search-api-net

  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - search-api-net

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command:
      [
        "--cassandra.keyspace=jaeger_v1_dc1",
        "--cassandra.servers=cassandra",
        "--collector.zipkin.http-port=9411",
      ]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema
    networks:
      - search-api-net

  jaeger-query:
    image: jaegertracing/jaeger-query
    command:
      ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema
    networks:
      - search-api-net

  cassandra:
    image: cassandra:3.9
    networks:
      - search-api-net

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    depends_on:
      - cassandra
    networks:
      - search-api-net

  watchdog:
    image: xabarilcoding/healthchecksui:2.2.35
    ports:
      - "6060:80"
    restart: always
    environment:
      HealthChecksUI:HealthChecks:0:Name: Search Api
      HealthChecksUI:HealthChecks:0:Uri: http://search-api/health
      HealthChecksUI:HealthChecks:1:Name: Dynadpater
      HealthChecksUI:HealthChecks:1:Uri: http://dynadapter/health
      HealthChecksUI:HealthChecks:3:Name: Sample Adapter
      HealthChecksUI:HealthChecks:3:Uri: http://sample-adapter/health
    networks:
      - search-api-net

  redis:
    container_name: redis
    image: redis
    hostname: ${REDIS__HOST}
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS__PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - search-api-net
    environment: 
      - REDIS_PASSWORD="${REDIS__PASSWORD}"
    volumes:
      - data-redis:/data
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander
    restart: always
    depends_on: [redis]
    networks: 
      - search-api-net
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=${REDIS__HOST}
      - REDIS_PASSWORD="${REDIS__PASSWORD}"
networks:
  search-api-net:
    driver: bridge

volumes:
  data-rabbit:
  data-redis:
