apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: web-adapter-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: web-adapter template
    description: |-
      This is a template for web-adapter.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: web-adapter-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
- description: Data partner service name.
  displayName: Name of the data partner service
  name: dataPartnerService
  required: true
  value:
- name: TAG
  required: true
  value: dev
objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${dataPartnerService}-web-adapter
      template: meta-service
    name: ${dataPartnerService}-web-adapter
  spec:
    host: ${dataPartnerService}-web-adapter-${namespacePrefix}-${TAG}.apps.silver.devops.gov.bc.ca
    to:
      kind: Service
      name: ${dataPartnerService}-web-adapter
      weight: 100
    wildcardPolicy: None
