apiVersion: v1
kind: Template
labels:
  template: search-api-scans-pipeline-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: search-api scans pipeline template
    description: |-
      This is a template for search-api scans pipeline.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: search-api-scans-pipeline-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
- description: Github trigger secret. A difficult to guess string encoded as part of the webhook URL. Not encrypted.
  displayName: GitHub Webhook Secret (Generated if empty)
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: gitSecret
- description: API definition, url pointing to swagger.json
  displayName: API definition
  name: apiDefinition
  required: true
  value:
- description: Sonarqube Raw Token
  displayName: Sonarqube Token
  name: sonartoken
  required: true
  value:
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      application: search-api
      template: master-build-pipeline
    name: search-api-scans-pipeline
    namespace: ${namespacePrefix}-tools
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/bcgov/fams3
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: search-api
        - name: API_DEFINITION
          value: ${apiDefinition}
        - name: LIFECYCLE_WEBHOOK
        - name: GIT_SOURCE_URL
          value: https://github.com/bcgov/fams3
        - name: GIT_SOURCE_REF
          value: master
        - name: GIT_CREDENTIALS_ID
          value:
        - name: SONAR_TOKEN
          value: ${sonartoken}
        - name: SONAR_PROJECT_KEY
          value: FAMS3-SearchApi
        - name: SONAR_URL
          value: http://sonarqube:9000
        - name: SONAR_COMMAND
        - name: SONAR_ENABLED
          value: "true"
        - name: TOOLS_NAMESPACE
          value: ${namespacePrefix}-tools
        - name: DEV_NAMESPACE
          value: ${namespacePrefix}-dev
        - name: TEST_NAMESPACE
          value: ${namespacePrefix}-test
        - name: PROD_NAMESPACE
          value: ${namespacePrefix}-prod
        jenkinsfile: |-
          try {
            // The API format; either openapi or soap
            def API_FORMAT = 'openapi'

            // The name  of the ZAP report
            def ZAP_REPORT_NAME = "zap-report.xml"

            // The location of the ZAP reports
            def ZAP_REPORT_PATH = "/zap/wrk/${ZAP_REPORT_NAME}"

            // The name of the "stash" containing the ZAP report
            def ZAP_REPORT_STASH = "zap-report"

            node("zap") {
              stage('ZAP Security Scan') {
                timeout(time: 60, unit: 'MINUTES') {

                  dir('zap') {
                    git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}", credentialsId: "${GIT_CREDENTIALS_ID}"
                    def retVal = sh (
                      returnStatus: true,
                      script: """
                        find
                        mkdir -p /zap/wrk/
                        mv app/SearchApi/zap/options.conf /zap/wrk/options.conf
                        cat /zap/wrk/options.conf
                        mv app/SearchApi/zap/default.context /zap/wrk/default.context
                        cat /zap/wrk/default.context

                        pwd
                        # sleep 3600

                        cp -r /var/lib/jenkins/.ZAP/policies /var/lib/jenkins/

                        zap-api-scan.py -t "${API_DEFINITION}" \
                          -f openapi \
                          -d \
                          -x ${ZAP_REPORT_NAME} \
                          -r ${APP_NAME}-zap-report.html \
                          -z "-configfile /zap/wrk/options.conf -d /var/lib/jenkins" \
                          -n /zap/wrk/default.context

                      """
                    )
                    echo "Return value is: ${retVal}"

                    // Copy the ZAP report into the Jenkins working directory so the Jenkins tools can access it.
                    sh (
                      returnStdout: true,
                      script: "mkdir -p ./wrk/ && cp ${ZAP_REPORT_PATH} ./wrk/"
                    )
                    // Copy the ZAP html report into the Jenkins working directory so the Jenkins tools can access it.
                    sh (
                      returnStdout: true,
                      script: "mkdir -p ./wrk/ && cp /zap/wrk/${APP_NAME}-zap-report.html ./wrk/"
                    )
                  }

                  // Stash the ZAP report for publishing in a different stage (which will run on a different pod).
                  echo "Stash the report for the publishing stage ..."
                  stash name: "${ZAP_REPORT_STASH}", includes: "zap/wrk/*.xml"
                  // Stash the ZAP report for publishing in a different stage (which will run on a different pod).
                  echo "Stash the report for the publishing stage ..."
                  stash name: "ZAP_REPORTS", includes: "zap/wrk/*.html"
                }
              }
            }

            node("base") {
              stage('Publish reports') {
                timeout(time: 60, unit: 'MINUTES') {
                  echo "Preparing the report for the publishing ..."
                  unstash name: "ZAP_REPORTS"

                  def retVal = sh (
                    returnStatus: true,
                    script: """
                      # find
                      export DATE_STAMP=\$(date +%Y-%m-%d-%H-%M-%S)
                      sed -ri "s/http:/https:/g" zap/wrk/${APP_NAME}-zap-report.html
                      [ -d "/var/www/html/reports/zap/" ] || mkdir -p /var/www/html/reports/zap
                      mv zap/wrk/${APP_NAME}-zap-report.html /var/www/html/reports/zap/\${DATE_STAMP}-${APP_NAME}-zap-report.html
                      cd /var/www/html/reports/zap/
                      rm -f 0000-00-00-00-00-00-${APP_NAME}-zap-report.html
                      ln -s \${DATE_STAMP}-${APP_NAME}-zap-report.html 0000-00-00-00-00-00-${APP_NAME}-zap-report.html
                    """
                  )
                }
              }
            }

            node("sonar-dotnet") {

              // Checkout Openshift metadata template
              stage("Checkout Templates") {
                dir("${APP_NAME}") {
                  git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}", credentialsId: "${GIT_CREDENTIALS_ID}"
                  env.GIT_COMMIT = getCommit()
                }
              }

              if ("${SONAR_ENABLED}"!="false") {
                stage("Sonar Scan") {
                  timeout(time: 10, unit: 'MINUTES') {

                    echo "Preparing the report for the publishing ..."
                    unstash name: "${ZAP_REPORT_STASH}"

                    withCredentials([usernamePassword(credentialsId: 'frjeow-tools-nexus-config', usernameVariable: 'NEXUS_REPO_USER', passwordVariable: 'NEXUS_REPO_PASSWORD')]) {
                      sh """
                      export NEXUS_REPO_URL=http://nexus:8081
                      echo ${GIT_COMMIT}
                      cd ${APP_NAME}/app/SearchApi
                      dotnet restore --configfile ../NuGet.config
                      dotnet test --logger:"trx;LogFileName=TestResults.trx" \
                                  /p:CollectCoverage=true \
                                  /p:CoverletOutputFormat=opencover \
                                  /p:CoverletOutput=./TestResults/
                      timeout -k 20 10 dotnet build-server shutdown || echo "Kill dotnet"
                      find
                      dotnet sonarscanner begin /k:"${SONAR_PROJECT_KEY}" \
                        /d:sonar.login=${SONAR_TOKEN} \
                        /d:sonar.host.url=${SONAR_URL} \
                        /d:sonar.cs.opencover.reportsPaths=./*Test/TestResults/coverage.opencover.xml \
                        /d:sonar.cs.vstest.reportsPaths=./*Test/TestResults/TestResults.trx \
                        /d:sonar.zaproxy.reportPath=${WORKSPACE}${ZAP_REPORT_PATH}
                      dotnet build
                      dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}
                      """
                    }
                  }
                }
              }
            }
          } catch (err) {
            echo "in catch block"

            currentBuild.result = 'FAILURE'
            env.ERR = "${err}"
            node {
                sh "curl -XPOST '${LIFECYCLE_WEBHOOK}' -H 'Content-type: application/json' --data '{\"username\":\"The Pipe Lion\",\"icon_emoji\":\":lion_face:\",\"text\": \"${APP_NAME} Pipeline Failure - ${ERR}\"}'"
            }
            echo "Caught: ${err}"
            throw err
          }

          String getCommit() {
              return sh(script: 'git rev-parse HEAD', returnStdout: true)?.trim()
          }
      type: JenkinsPipeline
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - github:
        secret: ${gitSecret}
      type: GitHub
