---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sonar
parameters:
- name: NAME
  displayName: Name
  description: A name used for all objects
  required: true
  value: sonar-runner
- name: IMAGE
  displayName: Image Namespace
  description: Docker registry reference image
  required: true
- name: SONAR_HOST_URL
  displayName: SonarQube host
  description: SonarQube server
  required: true
  value: https://sonarqube-frjeow-tools.pathfinder.gov.bc.ca
- name: DB_CONFIG_NAME
  displayName: Database Config Name
  description: Configuration name for the database
  required: true
- name: GIT_BRANCH
  description: Current git branch name
  required: true
- name: CPU_LIMIT
  value: 500m
- name: MEMORY_LIMIT
  value: 1.5Gi
- name: CPU_REQUEST
  value: 200m
- name: MEMORY_REQUEST
  value: 1Gi
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels: {}
  spec:
    containers:
    - name: test
      image: "${IMAGE}"
      command:
      - container-entrypoint
      - bash
      - "-c"
      - "./run_tests.sh"
      resources:
        limits:
          cpu: "${CPU_LIMIT}"
          memory: "${MEMORY_LIMIT}"
        requests:
          cpu: "${CPU_REQUEST}"
          memory: "${MEMORY_REQUEST}"
      env:
      - name: SONAR_HOST_URL
        value: "${SONAR_HOST_URL}"
      - name: GIT_BRANCH
        value: "${GIT_BRANCH}"
      imagePullPolicy: Always
    restartPolicy: Never
    activeDeadlineSeconds: 900
    dnsPolicy: ClusterFirst
  status: {}
