apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dynadapter-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: dynadapter template
    description: |-
      This is a template for dynadapter.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: dynadapter-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    labels:
      app: dynadapter
      template: meta-service
    name: dynadapter
  spec:
    ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: dynadapter
    sessionAffinity: None
    type: ClusterIP
