version: '3.7'
services:
  search-api:
    build:
      context: .
    environment:
      JAEGER_SERVICE_NAME: search-api
      JAEGER_AGENT_HOST: jaeger-agent
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: const
    ports:
      - "5050:80"
    networks: 
      - search-api-net
    
  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema
    networks: 
    - search-api-net

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema
    networks: 
    - search-api-net

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector
    networks: 
    - search-api-net

  cassandra:
    image: cassandra:3.9
    networks: 
    - search-api-net

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    depends_on:
      - cassandra
    networks: 
    - search-api-net

networks:
  search-api-net: