apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: fams3-pipeline
    template: fams3-pipeline-template
  name: fams3-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: ocp4
      uri: "https://github.com/bcgov/fams3"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/.pipeline/Jenkinsfile.ocp4
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
      type: GitHub
