apiVersion: v1
kind: Template
labels:
  template: dynadapter-config
message: |-
  dynadapter config template.
metadata:
  annotations:
    description: |-
      dynadapter config template.
    tags: dynadapter-config
    template: dynadapter-config
  name: dynadapter-config

# Parameters
parameters:
- name: CRON
  required: true
  value: "set.cron like '0/5 * * * * ?' "
- name: URL
  required: true
  value: "set.url.com"
- name: ADP
  required: true
  value: "set.adp"
- name: FAILEDCRON
  required: true
  value: "set.cron for failure retry like '0/5 * * * * ?' "
- name: DYNADAPTORAPIKEY
  required: true
  value: "set.api.key"
- name: TRUSTEDHOSTS
  required: true
  value: "*"

# Objects
objects:

- apiVersion: v1
  stringData:
    SCHEDULER__CRON: ${CRON}
    SEARCHAPI__BASEURL: ${URL}
    DYNADAPTOR_APIKEY: ${DYNADAPTORAPIKEY}
    SCHEDULER__FAILED: ${FAILEDCRON}
    SEARCHAPI__AVAILABLEDATAPARTNER: ${ADP}
    TRUSTEDHOSTS: ${TRUSTEDHOSTS}
  kind: Secret
  metadata:
    name: dynadapter-config
