apiVersion: v1
kind: Template
labels:
  template: fams3-github-key
message: |-
  fams3-github-key template.
metadata:
  annotations:
    description: |-
      fams3-github-key template.
    tags: fams3-github-key
    template: fams3-github-key
  name: fams3-github-key

# Parameters
parameters:
- description: The git ssh private key to access/write git repo (synced to Jenkins Credential Store)
  displayName: Git ssh private key
  name: gitSshPrivateKey
  value: c2V0LnNzaC1wcml2YXRlLWtleQ==

# Objects
objects:

- apiVersion: v1
  data:
    ssh-privatekey: >-
      ${gitSshPrivateKey}
  kind: Secret
  metadata:
    labels:
      credential.sync.jenkins.openshift.io: 'true'
    name: fams3-github-key
  type: kubernetes.io/ssh-auth