apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ia-sftp-config
message: |-
  SFTP config template.
metadata:
  annotations:
    description: |-
      SFTP config template.
    tags: ia-sftp-config
    template: ia-sftp-config
  name: ia-sftp-config
# Objects
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ia-sftp-config
    label:
      app: ia-search-web-adatper
  stringData:
    SFTP__CERTPATH: "set.certpath"
    SFTP__PASSWORD: "set.password"
    SFTP__PORT: "set.port"
    SFTP__SERVER: "set.server"
    SFTP__USERNAME: "set.username"
