apiVersion: v1
kind: Template
labels:
  template: rest-config
message: |-
  Rest Inbound config template.
metadata:
  annotations:
    description: |-
      Rest Inbound onfig template.
    tags: rest-inbound-config
    template: rest-inbound--config
  name: rest-inbound--config

# Parameters
parameters:
- name: APP_NAME
  required: true
  value: "set.app.name"
- name: PROFILE_NAME
  required: true
  value: "set.name"

# Objects
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-rest-inbound-config
    label:
      app: ${APP_NAME}
  stringData:
    PROVIDERPROFILE__NAME: ${PROFILE_NAME}

