apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: rest-inbound-adapter-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: rest-inbound-adapter image stream template
    description: |-
      This is a template for rest-inbound-adapter image stream.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: rest-inbound-adapter-imagestream-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
- description: Data partner service name.
  displayName: Name of the data partner service
  name: dataPartnerService
  required: true
  value:
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      application: ${dataPartnerService}-rest-inbound-adapter
    name: ${dataPartnerService}-rest-inbound-adapter
    namespace: ${namespacePrefix}-tools