name: Sonar Scan

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: pwd && ls -ll
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Run sonarqube
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet tool install --global dotnet-sonarscanner && source /etc/profile && cd app/DynamicsAdapter && ls -ll && dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=${{ secrets.SONAR_HOST_URL }}  && dotnet build && dotnet sonarscanner  /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=${{ secrets.SONAR_HOST_URL }} || exit 1
